Repository jethronap/jstat, pull requests merged in 2019-09, with the labels that each got.

#6 Fix bug with add/set values for NumericalSampleBase class
  src/main/java/datastructs/CategoricalSample.java
  src/main/java/datastructs/ContinuousSample.java
  src/main/java/datastructs/DiscreteSample.java
  src/main/java/datastructs/NumericSample.java
  src/main/java/datastructs/NumericSampleBase.java
  src/main/java/examples/UseContinuousSample.java
  src/main/java/utils/ArrayOperations.java
  src/test/java/stats/ResampleTest.java
  src/test/java/stats/ResampleTestRunner.java
  src/test/java/utils/ArrayOperationsTest.java
Labels: enhancement

#7 Create dataloader classes
  .gitignore
  1.0.0.iml
  README.md
  pom.xml
  src/main/java/dataloader/CsvDataLoader.java
  src/main/java/dataloader/JsonDataLoader.java
  src/main/main.iml
  src/test/java/dataloader/CsvLoaderTest.java
  src/test/java/dataloader/CsvLoaderTestRunner.java
  src/test/java/dataloader/JsonLoaderTest.java
  src/test/java/dataloader/JsonLoaderTestRunner.java
  test_data/dummy.csv
  test_data/dummy.json
  test_data/dummy_array.json
Labels: new feature

#9 Create examples and tests
  README.md
  data/robot_state.csv
  pom.xml
  src/main/java/base/Configuration.java
  src/main/java/dataloader/CsvDataLoader.java
  src/main/java/dataloader/utils/ParseUtils.java
  src/main/java/datastructs/CategoricalSample.java
  src/main/java/datastructs/ISample.java
  src/main/java/datastructs/NumericSample.java
  src/main/java/examples/LoadCsvDataSetWithTreeMap.java
  src/main/java/examples/MeanBootstrapExample.java
  src/main/java/examples/UseBootstrap.java
  src/main/java/examples/UseContinuousSample.java
  src/main/java/examples/UseContinuousSampleExample.java
  src/main/java/stats/utils/Resample.java
  src/test/java/dataloader/CsvLoaderTest.java
  src/test/java/datastructs/CategoricalSampleTest.java
  src/test/java/datastructs/CategoricalSampleTestRunner.java
  src/test/java/stats/ResampleTest.java
  test_data/robot_state_test.csv
Labels: documentation, enhancement

#10 Create examples and tests v2
  README.md
  data/humans_data.csv
  src/main/java/dataloader/CsvDataLoader.java
  src/main/java/datastructs/CategoricalSample.java
  src/main/java/examples/LoadCsvDataSetWithMap.java
  src/main/java/examples/LoadCsvDataSetWithMapAndExtractCategoricalSample.java
  src/main/java/examples/MeanBootstrap.java
  src/main/java/examples/UseContinuousSample.java
  src/test/java/dataloader/CsvLoaderTest.java
  src/test/java/dataloader/JsonLoaderTest.java
  src/test/java/datastructs/CategoricalSampleTest.java
  src/test/java/stats/ResampleTest.java
Labels: enhancement

#29 fix broken resample tests
  src/main/java/stats/utils/Resample.java
  src/test/java/stats/ResampleTest.java
Labels: bug, testing

#30 #24 Fix broken Json Loader test
  src/test/java/dataloader/JsonLoaderTest.java
Labels: bug, testing

#32 #22 create factory for loading tests
  src/test/java/AllTestsRunner.java
  src/test/java/dataloader/CsvLoaderTestRunner.java
  src/test/java/dataloader/JsonLoaderTestRunner.java
  src/test/java/datastructs/CategoricalSampleTestRunner.java
  src/test/java/datastructs/NumericSampleTestRunner.java
  src/test/java/stats/ResampleTestRunner.java
  src/test/java/testutils/ITestRunnerBase.java
  src/test/java/utils/ArrayOperationsTestRunner.java
Labels: documentation, enhancement

#34 Add student hypothesis testing
  README.md
  src/main/java/examples/HypothesisTestingForMean.java
Labels: enhancement

#36 #35 Add StatisticsType enumeration
  src/main/java/stats/StatisticsType.java
Labels: enhancement

#12 Create visualization classes
  .gitignore
  1.0.0.iml
  README.md
  jstat.iml
  pom.xml
  src/main/java/dataloader/CsvDataLoader.java
  src/main/java/dataloader/utils/ParseUtils.java
  src/main/java/datastructs/NumericSample.java
  src/main/java/examples/PlotABar.java
  src/main/java/examples/PlotALine.java
  src/main/java/examples/PlotAPie.java
  src/main/java/visualizations/BarChart.java
  src/main/java/visualizations/LineChart.java
  src/main/java/visualizations/PieChart.java
  src/main/main.iml
  src/test/java/dataloader/CsvLoaderTest.java
  src/test/java/visualizations/BarChartTest.java
  src/test/java/visualizations/BarChartTestRunner.java
  src/test/java/visualizations/LineChartTest.java
  src/test/java/visualizations/LineChartTestRunner.java
  src/test/java/visualizations/PieChartTest.java
  src/test/java/visualizations/PieChartTestRunner.java
  test_data/annual.csv
  test_data/dummy.csv
  test_data/humans_data.csv
Labels: enhancement

#26 Create histograms
  README.md
  src/main/java/datastructs/NumericSample.java
  src/main/java/examples/PlotAHistogram.java
  src/main/java/examples/PlotAScatter.java
  src/main/java/visualizations/Histograms.java
  src/main/java/visualizations/ScatterChart.java
  src/test/java/visualizations/BarChartTest.java
  src/test/java/visualizations/BarChartTestRunner.java
  src/test/java/visualizations/LineChartTest.java
  src/test/java/visualizations/LineChartTestRunner.java
  src/test/java/visualizations/PieChartTest.java
  src/test/java/visualizations/PieChartTestRunner.java
Labels: enhancement

#23 Create scatter plots
  README.md
  data/annual.csv
  src/main/java/dataloader/CsvDataLoader.java
  src/main/java/datastructs/NumericSample.java
  src/main/java/examples/PlotABar.java
  src/main/java/examples/PlotALine.java
  src/main/java/examples/PlotAPie.java
  src/main/java/examples/PlotAScatter.java
Labels: enhancement
